### ISSUE TITLE
Should it be possible to close out the result box if a user clicks the grey outside area?

### ISSUE THREAD

**Issue by webmasterkai** [cape-io/deluxe-quiz#3]

**Comment by esauer** [comment]
Yes. Let's let them take that AMAZING quiz again if they like! However, this means we should add the same "see how it works (link to website you don't have) " red box at the bottom of the quiz. Possible? AND THANK you for asking that question. :)

**Comment by esauer** [comment]
HI, 

I will be leaving the office for the day around 5, but would take a peek at something tomorrow if you are cool with that. :)

**Comment by webmasterkai** [comment]
This should working now. When the submit button is grey when you first load the page you know you're looking at the latest. Might take a few minutes before i shows up.
