### ISSUE TITLE
prevent whitespace below footer

### ISSUE THREAD

**Issue by webmasterkai** [cape-io/deluxe-quiz#4]
If you zoom out enough and stretch the window tall enough white space shows below the grey footer.
@bjornmeansbear or @tlupfer Can you make it so there is no white space below the footer? Something about the main container not getting 100% height or some such...

Thanks!

![footer](https://www.dropbox.com/s/el2syz3zreecczq/Screenshot%202016-01-18%2011.50.06.png?dl=1)

**Comment by tlupfer** [comment]
on it!

**Comment by bjornmeansbear** [comment]
5d20b6898694dc65f56455d79beb400686eedc87 and 762db001f3f89d2764f0457520345c8c80fcc1dc should take care of this.
