### ISSUE TITLE
score-box and score-words should both vertical align on parent height

### ISSUE THREAD

**Issue by webmasterkai** [cape-io/deluxe-quiz#6]
Currently score-text looks to be align top, should be middle.

Currently looks like:
![](https://www.dropbox.com/s/1ps0s1u4pksbbcd/Screenshot%202016-01-18%2013.56.43.png?dl=1)

Should look like:
![](https://www.dropbox.com/s/i8dms3lcgavf7x8/Screenshot%202016-01-18%2014.30.32.png?dl=1)

**Comment by bjornmeansbear** [comment]
this is the worst thing to try and fix :)
but I can make this work.
